### ISSUE TITLE
ERROR: librtmp not found

### ISSUE THREAD

**Issue by OliverLetterer** [chrisballinger/FFmpeg-iOS#2]
first of all thank you for these build scripted.

my goal was to compile a custom version of ffmpeg with your build scripts but im running into a small problem when compiling with the **default settings** which i dont quiet understand and was hoping you had a bit feedback or knowhow about this issue:
- i cloned this repository and installed the latest version of gas-preprocessor.pl
- i ran `./build-libssl.sh` and `./build-librtmp.sh` with success and am seeing libcrypto.a, librtmp.a and libssl.a in `dependencies/lib` and their corresponding header files in `dependencies/include`
- then executing `./build-ffmpeg.sh` results in the following output:

```
Downloading ffmpeg-2.2.tar.bz2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 6860k  100 6860k    0     0  2518k      0  0:00:02  0:00:02 --:--:-- 2519k
Building without ccache
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
ERROR: librtmp not found

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
Include the log file "config.log" produced by configure as this will help
solving the problem.
```

i can figure out why librtmp isn't found because it exists in `dependencies/lib` and the linker flags seem to be correct `--extra-ldflags="... -L${OUTPUTDIR}/lib"`

**Comment by kpkumarkpk** [comment]
I  would like to use FFmpeg for video comressing video file but  I dont know how to configure to xcode project and how to apply code for video compressing
